kind: Template
apiVersion: v1
metadata:
  name: devops-toolkit
objects:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: gogs.example.redhat.com
  spec:
    group: example.redhat.com
    names:
      kind: Gogs
      listKind: GogsList
      plural: gogs
      singular: gogos
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
    versions:
    - name: v1alpha1
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: jenkins.example.redhat.com
  spec:
    group: example.redhat.com
    names:
      kind: Jenkins
      listKind: JenkinsList
      plural: jenkins
      singular: jenkins
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
    versions:
    - name: v1alpha1
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: sonarqubes.example.redhat.com
  spec:
    group: example.redhat.com
    names:
      kind: SonarQube
      listKind: SonarQubeList
      plural: sonarqubes
      singular: sonarqube
    scope: Namespaced
    subresources:
      status: {}
    version: v1alpha1
    versions:
    - name: v1alpha1
      served: true
      storage: true
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRole
  metadata:
    labels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
    name: devopstools-aggregate-to-admin
  rules:
  - apiGroups:
    - apps
    resources:
    - deployments/finalizers
    verbs:
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - example.redhat.com
    resources:
    - '*'
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: devops-tools-operator
- kind: RoleBinding
  apiVersion: authorization.openshift.io/v1
  metadata:
    name: devops-tools-operator
  subjects:
  - kind: ServiceAccount
    name: devops-tools-operator
  roleRef:
    name: admin
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: devops-tools-operator
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: devops-tools-operator
    template:
      metadata:
        labels:
          name: devops-tools-operator
      spec:
        serviceAccountName: devops-tools-operator
        containers:
          - name: ansible
            command:
            - /usr/local/bin/ao-logs
            - /tmp/ansible-operator/runner
            - stdout
            # Replace this with the built image name
            image: "docker-registry.default.svc:5000/openshift/devops-tools-operator:latest"
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
              readOnly: true
          - name: operator
            # Replace this with the built image name
            image: "docker-registry.default.svc:5000/openshift/devops-tools-operator:latest"
            imagePullPolicy: Always
            volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
            env:
              - name: WATCH_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: OPERATOR_NAME
                value: "devops-tools-operator"
        volumes:
          - name: runner
            emptyDir: {}
