apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: devopstools.example.redhat.com
spec:
  group: example.redhat.com
  names:
    kind: DevOpsTools
    listKind: DevOpeToolsList
    plural: devopstools
    singular: devopstools
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
