galaxy_info:
  author: Takashi Nishigaya
  description: Role to set up CodeReady Workspaces from Operator.
  company: Red Hat
  license: Apache
  min_ansible_version: 2.6
  galaxy_tags:
    - openshift
    - kubernetes
    - k8s
    - ansible-operator
    - rhamt
dependencies: []
