---
# tasks file for pathfinder-ocp
- name: Verify that dc/mongodb exists
  k8s_facts:
    kind: DeploymentConfig
    name: mongodb
    namespace: "{{ _pathfinder_namespace }}"
  register: mongodb_dc

- name: Deploy/Undeploy MongoDB using template
  when:
    - (_pathfinder_enabled and mongodb_dc.resources == []) or
      (not _pathfinder_enabled and mongodb_dc.resources != [])
  shell: |
    oc get template mongodb-persistent -o yaml -n openshift | \
      oc process -f - -p MONGODB_DATABASE=pathfinder --local | \
      oc {{ create_or_delete }} -f - -n {{ _pathfinder_namespace }}
  vars:
    create_or_delete: "{{ _pathfinder_enabled | ternary('create', 'delete') }}"

- name: Verify that MongoDB Pod is running
  when:
    - _pathfinder_enabled
  k8s_facts:
    kind: Pod
    label_selectors:
      - name = mongodb
    namespace: "{{ _pathfinder_namespace }}"
  register: mongodb_pod
  until:
  - mongodb_pod.resources != []
  - mongodb_pod.resources[0].status.phase == "Running"
  retries: 20
  delay: 5

- name: Verify that dc/pathfinder-* exists
  k8s_facts:
    kind: DeploymentConfig
    label_selectors:
      - bundle = pathfinder
    namespace: "{{ _pathfinder_namespace }}"
  register: pathfinder_dc

- name: Deploy/Undeploy PathFinder using template
  when:
    - (_pathfinder_enabled and pathfinder_dc.resources == []) or
      (not _pathfinder_enabled and pathfinder_dc.resources != [])
  shell: |
    oc process -f {{ role_path }}/files/pathfinder-full-template.yaml \
      -p IMAGES_REGISTRY={{ _pathfinder_images_registry }} \
      -p IMAGES_NAMESPACE={{ _pathfinder_images_namespace }} \
      -p IMAGES_TAG={{ _pathfinder_images_tag }} | \
      oc {{ create_or_delete }} -f - -n {{ _pathfinder_namespace }}
  vars:
    create_or_delete: "{{ _pathfinder_enabled | ternary('create', 'delete') }}"

- name: Verify that PathFinder Pod is running
  when:
    - _pathfinder_enabled
  k8s_facts:
    kind: Pod
    label_selectors:
      - app = pathfinder-server
    namespace: "{{ _pathfinder_namespace }}"
  register: pathfinder_pod
  until:
  - pathfinder_pod.resources != []
  - pathfinder_pod.resources[0].status.phase == "Running"
  retries: 50
  delay: 5
