---
# DevOps Tools playbook.
#
# The following variables come from the ansible-operator
# - meta.namespace
# - meta.name (from the name of the CR)

- hosts: localhost
  gather_facts: no
  tasks:
  - name: Set up Jenkins
    include_role:
      name: ./roles/jenkins-ocp
    vars:
      _jenkins_state: "{{ jenkins.enabled | ternary('present', 'absent') }}"
      _jenkins_namespace: "{{ meta.namespace }}"
#      _jenkins_name: "{{ meta.name }}"
      _jenkins_oauth: "{{ jenkins.useOAuth | d(true) }}"
      _jenkins_memory_limit: "{{ jenkins.memoryLimit | d('1Gi') }}"
      _jenkins_volume_size: "{{ jenkins.volumeSize | d('1Gi') }}"
      _jenkins_disable_administrative_monitors: "{{ jenkins.jenkinsDisableAdministrativeMonitors | d(false) }}"
      _jenkins_plugins: "{{ jenkins.plugins | d('') }}"
